---
- name: Установка dnsmasq
  apt:
    name: dnsmasq
    state: present

- name: Создание конфигурационного файла dnsmasq
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
  notify: Перезапуск dnsmasq

- name: Включение и запуск службы dnsmasq
  systemd:
    name: dnsmasq
    enabled: yes
    state: started
